const main = () => {
  const suggestions = {
    location: [
      'Operating Room',
      'Driveway',
      'Stables',
      'Kitchen',
      'Walk-In Closet',
      'Man Cave',
      'Garage at Home',
      "Mechanic's Garage",
      'Executive Office',
      'Oval Office',
      'Apollo Capsule',
      'Torture Chamber',
      'Medieval Dungeon',
      'Safe Room',
      'Hotel Lobby',
      'Weight Room',
      'Tailor',
      'Change Room at a Store',
      'Café',
      'Terrasse',
      'Dr. Office',
      'Lawyer Office',
      'Boat Deck',
      'Sauna',
      'Hot Tub',
      'Singles Bar',
      "Star's Dressing Room",
      'Batcave',
      'Limo',
      'Ambulance',
      'Private Jet',
      "Hoarder's Shed",
      'Green House',
      'Billiard Room',
      'Library',
      'Dorm Room',
      'Brewery',
      'Basement',
      'Attic',
      'Storage Locker',
      'Bike Shop',
      'Artist Studio',
      'Hayloft',
      'Back Alley',
      'Jail Cell',
      'Moving Van',
      'Stasis Chamber',
      'Beach',
      'Poker Room',
      'Ball Pit',
      "Butcher's",
      'Meat Freezer',
      'Boxing Ring',
      "Jeweller's",
      'Sweat Shop',
      'Candy Store',
      'Antiques Store',
      'Museum Storage',
      'Classroom',
      "Teacher's Lounge",
      'VIP Lounge',
      'Airport Gate',
      'Morgue',
      'Abandoned Home',
      'Trailer Home',
      'Campsite',
      'Cave',
      'Sinkhole',
      'Quicksand',
      'Military Tent',
      'Ladies Restroom',
      "Men's Restroom",
      'Penthouse Apt',
      'Slum Apt',
      'Bus',
      'English Pub',
      'Shoe Shop',
      'Recording Studio',
      'Observatory',
      'Ice Fishing Shack',
      'Cockpit',
      'Bank',
      'Dep/Bodega/Convenience Store',
      'Florist',
      'Rowboat',
      'Life Raft',
      'Yoga Class',
      'Dance Hall',
      'Skate Park',
      'Playground',
      'Golf Green',
      'Bus Stop',
      'Vintage Shop',
      'Museum Room',
      'Workshop',
      'Tennis Court',
      'Food Cart/Truck',
      'Courtroom',
      'Photobooth',
      'Fallout Shelter',
      'Hobo Rail Car',
      'Wine Cellar',
      'Hot Dog Stand',
      'Hair Salon',
      'Airlock',
      'Subway Car',
      'Balcony',
      'Arcade',
      'Birthday Party',
      'Ice Cream Shop',
      'Dairy Farm',
      'Veterinary Office',
      'Computer Lab',
      'Top Secret Meeting Room',
      'Bank Vault',
      'Outdoors ATM',
      'Logging Camp',
      'Fishing Dock',
      'Rowboat',
      'Flooding Basement',
      'Haunted House',
      'Sleepover',
      'Bunk Beds',
      'University Corridor',
      'Wealthy Manor',
      'Seaside Cottage',
      'Small Town Grocery Store',
      'Organic Grocery Store',
      'Fruit Market',
      'Apple Orchard',
      'Amazon Jungle',
      'Apiary',
      'Florist',
      'Wedding Reception',
      'Baby Shower',
      'Daycare',
      'Kindergarten Class',
      'High School Cafeteria',
      'Driving School',
      "Carpenter's Studio",
      'Hardware Store',
      'Customer Service Desk',
      'Call Center',
      'Reception Desk',
      'Kangaroo Pouch',
      'Moonbase Bravo',
      'Doomed Spaceship',
      'Asteroid Mine',
      'Old West Town',
      'Desert',
      'A Blizzard',
      'Comic Con',
      'Heritage Theatre',
      'Art Gallery',
      "World's Biggest Shoe",
      'TV Studio',
      'Dolphin Research Lab',
      'Hamster Cage',
      'Blood Stream',
      'Murder Scene',
      '70s Disco Club',
      '60s Drum Circle',
      '50s Suburbs',
      '80s Mall',
      '90s Music Festival',
      'Flash Mob',
      'Bed N Breakfast',
      'Goblin Hut',
      "Dragon's Cave",
      'Labyrinth',
      'Gladiator Ring',
      'Coronation',
      'Ice Cave',
      'Car Dealership',
      'Security Bunker',
      'Airplane Seats',
      'Used Book Shop',
      'Virtual Reality',
      'The Afterlife',
      'Battery Factory',
      'Carousel',
      'Palace',
      "Servant's Quarters",
      'Formula 1 Garage',
      'Betting Parlour',
      'Backstage',
      'Ballet Studio',
      'Raspberry Field',
      'Ditch',
      'Mud Pit',
      'Circus Tent',
      'Newspaper Office',
      'Tailor',
      'World of Dreams',
      'Alligator World',
      "Dentist's Chair",
      'Mt. Everest Base Camp',
      'Donut Shop',
      'Planet MB-204',
      'Junkyard',
    ],
    relationship: [
      'Bus Driver/A Regular',
      'Bartender/Waitress',
      'Cook/Sous-Chef',
      'Schoolbus Driver/The Last Kid',
      'EMT/Cop',
      'Team Owner/Superstar',
      'Two Shoe Designers',
      'Watchermaker/Apprentice',
      'X-Ray Tech/Doctor',
      'Vampire/Werewolf',
      'Millionaire/Yacht Salesman',
      'Producer/Manager',
      'Gardener/Pool Boy',
      'Conductor/1st Violin',
      'Jockey/Vet',
      'Union Leader/CEO',
      'Skateboard Seller/Teenager',
      'Foreman/Architect',
      'Torturer/Jester',
      'Prince/Stablehand',
      'Dog Food Chef/Cat Food Chef',
      'Postal Worker/UPS Deliverer',
      'Buggy Driver/Car Owner',
      'Supervillian/Prison Guard',
      'Tatoo Artist/Piercer',
      'Baby/Pet',
      'Hostage/Robber',
      'Ambassador/King',
      'Spy/Handler',
      'Pitcher/Catcher',
      'Arms Dealer/Mom',
      'Mayor/Janitor',
      'Street Hustler/Off-Duty Cop',
      'Piano Tuner/Concept Artist',
      'Person/Future Self',
      'Newlywed/Bellhop',
      'Doctor/Assassin',
      'Hobo/Street Vendor',
      'Blacksmith/Jockey',
      'Astronaut/Mission Chief',
      'Tailor/Cobbler',
      'Foster Parent/Teen',
      'Entrepreneur/Bank Officer',
      'Dictator/General',
      'Socialite/Plumber',
      'Senator/Lobbyist',
      'Executive/Assistant',
      'Party Animal/Cop',
      'Spouse/Homewrecker',
      'Rival Explorers',
      'Principal/Teacher',
      'Astronomer/Meteor',
      'Theory/Experiment Physicist',
      'Forest Ranger/Camper',
      'Bear/Cub',
      'Landscaper/Homeowner',
      'Scriptwriter/Actor',
      'Programmer/Student',
      'Sailor/Lighthouse Keeper',
      'Pilot/Flight Tower',
      'Dentist/Patient',
      'Optometrist/Patient',
      'Pharmacist/Customer',
      'Nurse/Recovering Patient',
      'Midwife/Expecting Mother',
      'Two Judges',
      'Professor/Star Pupil',
      'Physical Trainer/Actor',
      'Archivist/Researcher',
      'Museum Curator/Politician',
      'Author/Editor',
      'Journalist/Informant',
      'Traveler/Translator',
      'Sculptor/Model',
      'Photographer/Camera Seller',
      'Bride/Wedding Planner',
      'Coach/Referee',
      "Chef/Maitre D'",
      'Hairdresser/Regular',
      'Telephone Operator/Caller',
      'Ticket Agent/Traveler',
      'Airplane Passengers',
      'Bartender/Regular',
      'Babysitter/New Parent',
      'Pet Groomer/Pet Owner',
      'Cashier/Customer',
      'Teenager/Mentor',
      'Security Guard/Janitor',
      'Woodsman/Camper',
      'Cyclist/Driver',
      'Rare Book Collectors',
      'Taxi Driver/Passenger',
      'Limo Driver/Trophy Spouse',
      'Kid/Parent',
      'Teen/Parent',
      'Teen/Grandparent',
      'Parent/Grandparent',
      'Logger/Forest Ranger',
      'Fishing Boat Captain/1st Mate',
      'Farmer/Scarecrow',
      'Spouse/Parent-In-Law',
      'Student/Rich Relative',
      'Stunt Driver/Director',
      'Forger/Crime Boss',
      'Castaway/Coconut',
      'Forest Guide/City Person',
      'Old Hunter/New Hunter',
      'Detective/Witness',
      'Astrologer/Regular Client',
      'Wizard/Pet Toad',
      'Bitcoin Expert/Millionaire',
      'Architect/CEO',
      'Rats',
      'UN Ambassador/Dictator',
      'Potential Investor/New CEO',
      'Biologist/Submarine Pilot',
      'Giant/Golden Goose',
      'Frog/Fly',
      'Sports Coach/Player',
      'Magician/Gambler',
      'Room Service/Hotel Visitor',
      'Cloud/Cactus',
      'Dancer/Artistic Director',
      'Actor/Understudy',
      'Tourist/Local Artist',
      'Car Mechanic/Street Racer',
      'Child/Monster Under The Bed',
      'Gold Miner/Gold Buyer',
      'Weather Forecaster/News Anchor',
      'Influencer/Photographer',
      'New Home Owner/Ghost',
      'Shy Person/Their Crush',
      'Person in Heaven/Angel',
      'Royalty/Knight',
      'New Parents',
      'Ants',
      'Violin Prodigy/Luthier',
      'Firefighter/Mayor',
      'Sommelier/Diner',
      'Gondola Pilot/Boat Inspector',
      'New Driver/License Examiner',
      'Twitch Streamer/Fan',
      'Pool Hustler/Gambler',
      'Florist/Newly in Love',
      'Zookeeper/Parrot',
      'Teacher/Student',
      'University Dean/Professor',
      'Politician/Biggest Donor',
      'Realtor/Home Buyer',
      'Chaperone/Teen on a Date',
      'Caller/Phone Operator',
      'Spaceship A.I./Captain',
      'Lost Sea Captain/Kraken',
      'Supermodel/Vampire',
      'Judge/Pickpocket',
      'Alien/President',
      'Movie Star/Accountant',
      'Cyclops/Odysseus',
      'Greenpeace/Whale',
      'Baker/Rich Idiot',
      'Plumber/Renter',
      'Busker/Dog Walker',
      'Guitarist/Roadie',
      'First-Time Lovers',
      'Best Friends',
      'NASA/Mars Astronaut',
      'Blind Date',
      'Cat/Mouse',
      'Frenemies',
      'Bored Aristocrats',
      'Welder/Cyclist',
      'Inventor/Distant Cousin',
      'Facebook-only Friends',
      'Perfectionist/Toddler',
      'Sandwich Maker/Client',
      'Rail Traveler/Ticket Inspector',
      'Opera Singer/Doctor',
      'Soup Slurper/Waiter',
      'Rally Driver/Navigator',
      'Person/Hallucination',
      'Gladiator/Betrothed',
      'Olympic Athlete/Judge',
      'Yo-Yo Artist/Agent',
      'Hacker/Bank Manager',
      'Life Coach/Client',
      'Bandit/Train Conductor',
      'Visual Artist/Curator',
      'Camper/Bear',
      'Tax Auditor/Citizen',
      'Tennis Pro/Manager',
      'Messenger/King',
      'Children Lost in the Woods',
      'Protestor/Bystander',
      'Butler/Head of the House',
      'Demon/Exorcist',
      'Croupier/Gambler',
      'Organ Donor/Recipient',
      'Mario/Koopa',
      'Slob/Tidy Roommate',
      'Philosopher/Apprentice',
    ],
    word: [
      'Commerce',
      'Constitution',
      'Patriot',
      'Pride',
      'Prejudice',
      'Speech',
      'Crowds',
      'Stadium',
      'Architect',
      'Blueprints',
      'Prince',
      'Princess',
      'Recess',
      'Government',
      'Elections',
      'President',
      'Resident',
      'House',
      'Home',
      'Hot',
      'Disagree',
      'Argument',
      'Couch',
      'TV',
      'Radio',
      'Internet',
      'Programming',
      'Alone',
      'Friends',
      'Trust',
      'Loan',
      'Borrow',
      'Interest',
      'Hobby',
      'Hotel',
      'Leaving',
      'Arriving',
      'Airport',
      'Jetlag',
      'Time Zone',
      'Shifting',
      'Uppercase',
      'Capitals',
      'Geography',
      'Cartography',
      'Maps',
      'Boots',
      'Marching',
      'Army',
      'Camping',
      'Nature',
      'Tree Planting',
      'Paper',
      'Pens',
      'Literacy',
      'Newspapers',
      'Journalism',
      'Weather',
      'Storm',
      'Hurricane',
      'Boxer',
      'UPS',
      'Overnight',
      'Moon',
      'Eclipse',
      'Dark',
      'Trapped',
      'Care',
      'Bats',
      'Batman',
      'Heroes',
      'Villains',
      'Comic Books',
      'Collector',
      'Flea Market',
      'Vintage',
      'Antiques',
      'Civil War',
      'Uniform',
      'Weapons',
      'Atom',
      'Translation',
      'Genius',
      'Genuine',
      'Forgery',
      'Painting',
      'Artist',
      'Poverty',
      'Charity',
      'Heart',
      'Love',
      'Platonic',
      'Greece',
      'Democracy',
      'Volunteer',
      'Tea',
      'Sugar',
      'Coffee',
      'Bitterness',
      'Lemon',
      'Salesman',
      'Theater',
      'Director',
      'Movies',
      'Actor',
      'Agent',
      'Spy',
      'Infiltrate',
      'Prison',
      'Guard',
      'Key',
      'Pie',
      'Circle',
      'Square',
      'Fair',
      'Unfair',
      'Rivalry',
      'Siblings',
      'Parents',
      'Pregnancy',
      'Rain',
      'Clouds',
      'Rorschach',
      'Psychology',
      'Auditorium',
      'Cafeteria',
      'Quad',
      'Pecs',
      'Six-pack',
      'Ten-Four',
      'Quarterback',
      'Goals',
      'Careers',
      'Directionless',
      'Hobo',
      'Packing',
      'Moving',
      'Mail',
      'Post Office',
      'Telegram',
      'Titanic',
      'Iceberg',
      'Lettuce',
      'Migrant',
      'Geese',
      'Foie Gras',
      'Cheese',
      'Ham',
      'Peanut Butter',
      'Tobacco',
      'Smoking',
      'Break Room',
      'Interview',
      'Vampire',
      'Ghost',
      'Haunted',
      'Trauma',
      'ER',
      'Blood',
      'Period',
      'Teenager',
      'Mall',
      'Milkshake',
      'Fountain',
      'Rome',
      'Soccer',
      'World Cup',
      'World Series',
      'WWII',
      'WWI',
      'Versailles',
      'Palace',
      'Salon',
      'Witty',
      'Kitten',
      'Laser',
      'Shark',
      'Pool',
      'Hustle',
      'Boston',
      'Accent',
      'London',
      'Medieval',
      'Jousting',
      'Armor',
      'Blacksmith',
      'Horseshoe',
      'Lucky',
      'Unlucky',
      'Unrequited',
      'Crush',
      'Pact',
      'Oath',
      'Oats',
      'Goats',
      'Cliff',
      'Canyon',
      'Burro',
      'Jockey',
      'Boxers',
      'Briefs',
      'Briefcase',
      'Minister',
      'Prime Minister',
      'Politics',
      'Debate',
      'Club',
      'Diamond',
      'Heart',
      'Shovel',
      'Cemetary',
      'Video Games',
      'Dungeon',
      'Hostage',
      'Negotiation',
      'Unions',
      'Big Business',
      'Savings',
      'Monument',
      'Statue',
      'Sculptor',
      'Da Vinci',
      'Notebook',
      'Journalism',
      'Expedition',
      'Exploring',
      'Adventure',
      'Quest',
      'Question',
      'Riddle',
      'Waffle',
      'Maple Syrup',
      'Beans',
      'Has Been',
      'Fame',
      'Infamous',
      'Wanted',
      'Outlaw',
      'Sheriff',
      'Showdown',
      'Sunset',
      'Refraction',
      'Vision',
      'Eloquence',
      'Password',
      'Encryption',
      'Hacker',
      'Pentagon',
      'Top Secret',
      'Taxonomy',
      'Astrology',
      'Twins',
      'Nonsense',
      'Codes',
      'Doors',
      'Elevator',
      'Escalator',
      'Exercise',
      'Fitness',
      'Purpose',
      'Porpoise',
      'Tortoise',
      'Glasses',
      'Nerd',
      'Jock',
      'Bimbo',
      'Ditz',
      'Blonde',
      'U-Turn',
      'Give Up',
      'Quit',
      'Logic',
      'Logo',
      'Arrows',
      'Slings',
      'Giant',
      'Dragon',
      'Treasure',
      'Locket',
      'Pop and Lock',
      'Disco',
      'Rap',
      'Country',
      'Anthem',
      'Revolution',
      'Regime',
      'Reggae',
      'Remix',
      'Studio',
      'Grammy',
      'Oscar',
      'Trashed',
      'Diva',
      'Diving',
      'Penalty',
      'Crowd',
      'Tickets',
      'Sold Out',
      'Sell Out',
      'Rock Star',
      'Contract',
      'Expand',
      'Pond',
      'Time Travel',
      'Paradox',
      "Pandora's Box",
      'Present',
      'Part',
      'Future',
      'Sci-Fi',
      'Jetpack',
      'Supersonic',
      'Sonic Boom',
      'Fighter',
      'Lover',
      'Confession',
      'Church',
      'Holy',
      'Smoke',
      'Detector',
      'Detective',
      'Rejected',
      'Ejected',
      'Dejected',
      'Depression',
      'Hiding',
      'Bully',
      'Playing',
      'Slacking',
      'Laziness',
      'Sleep',
      'Experiment',
      'Academic',
      'Presentation',
      'Christmas',
      'Hunger',
      'Hanging',
      'Execution',
      'Anonymous',
      'Addiction',
      'Treatment',
      'Trick or Treat',
      'Disguise',
      'Mask',
      'Cowboy',
      'Fired',
      'Jobs',
      'Paycheck',
      'Casino',
      'Luxury',
      'Taxes',
      'Dome',
      'Bomb',
      'Sphere',
      'Biosphere',
      'Planet',
      'Space',
      'Comets',
      'The Sun',
      'Sunburn',
      'Beach',
      'Towel',
      'Shower',
      'Soap',
      'Dishwasher',
      'Kitchen',
      'Cook',
      'Hat',
      'Winter',
      'Summer',
      'Fall',
      'Spring',
      'Mattress',
      'Bed',
      'Seduction',
      'Subtraction',
      'Math',
      'Chemistry',
      'Dating',
      'Breaking Up',
      'Anger',
      'Revenge',
      'Murder',
      'Tickling',
      'Children',
      'Birth',
      'Pregnancy',
      'Surprise',
      'Attack',
      'Defensive',
      'Guilty',
      'Innocence',
      'Virgin',
      'Cocktail',
      'Bar',
      'Bartender',
      'Tipping',
      'Cows',
      'Milk',
      'Surgery',
      'Sterile',
      'Spaceship',
      'Vacuum',
      'Dust',
      'Ashes',
      'Cricket',
      'Baseball',
      'Umpire',
      'Referee',
      'Hockey',
      'Trophy',
      'Wife',
      'Husband',
      'Wedding',
      'Divorce',
      'Court',
      'Judge',
      'Jury',
      'Executioner',
      'Guillotine',
      'Aristocrat',
      'Peasant',
      'Farm',
      'Tractor',
      'Property',
      'Manners',
      'Table',
      'Chairs',
      'Chairman',
      'CEO',
      'Stocks',
      'Trading',
      'Cards',
      'Birthday',
      'Cake',
      'Chocolate',
      'Vanilla',
      'Ice Cream',
      'Cones',
      'Traffic',
      'Drugs',
      'Mental',
      'Health',
      'Wealth',
      'Vault',
      'Pole',
      'Tall',
      'Short',
      'Temper',
      'Sword',
      'Samurai',
      'Japan',
      'China',
      'Registry',
      'Engaged',
      'Rings',
      'Olympics',
      'Silver',
      'Stains',
      'Laundry',
      'River',
      'Squad',
      'Rumble',
      'Earthquake',
      'Sway',
      'Influence',
      'Unfocussed',
      'Control',
      'Overwhelmed',
      'Rushed',
      'Pressure',
      'Apathy',
      'Indifferent',
      'Helpless',
      'Frightened',
      'Worried',
      'Inadequate',
      'Inferior',
      'Worthless',
      'Insignificant',
      'Exclude',
      'Persecute',
      'Nervous',
      'Exposed',
      'Betray',
      'Resent',
      'Disrespect',
      'Ridicule',
      'Indignant',
      'Furious',
      'Jealous',
      'Provoke',
      'Hostile',
      'Infuriated',
      'Annoyed',
      'Withdrawn',
      'Numb',
      'Sceptical',
      'Dismissive',
      'Judgmental',
      'Embarrassed',
      'Appalling',
      'Revolted',
      'Nausea',
      'Destestable',
      'Horrifed',
      'Hesitant',
      'Shocked',
      'Dismay',
      'Disillusioned',
      'Perplexed',
      'Astonished',
      'Awe',
      'Eager',
      'Energetic',
      'Cheeky',
      'Free',
      'Joyful',
      'Curious',
      'Inquisitive',
      'Successful',
      'Confident',
      'Respect',
      'Value',
      'Courageous',
      'Creative',
      'Loving',
      'Thankful',
      'Sensitive',
      'Intimate',
      'Hopeful',
      'Inspiration',
      'Isolate',
      'Abandon',
      'Victim',
      'Fragile',
      'Grief',
      'Powerless',
      'Disappointment',
      'Empty',
      'Remorse',
      'Shame',
      'Playful',
      'Content',
      'Interest',
      'Proud',
      'Accept',
      'Powerful',
      'Peaceful',
      'Trust',
      'Optimism',
      'Excited',
      'Startled',
      'Confused',
      'Amaze',
      'Bored',
      'Busy',
      'Stress',
      'Tired',
      'Scared',
      'Anxious',
      'Insecure',
      'Weak',
      'Rejection',
      'Threaten',
      'Bitter',
      'Aggression',
      'Frustration',
      'Distant',
      'Critical',
      'Lonely',
      'Lovely',
      'Despair',
      'Guilty',
      'Hurt',
      'Despair',
      'Disapprove',
      'Awful',
      'Boiling',
      'Date',
      'Time',
      'Hour',
      'Minute',
      'Seconds',
      'Calendar',
      'Year',
      'Download',
      'Follow',
      'Icon',
      'Record',
      'Switch',
      'Bluetooth',
      'Camera',
      'Zoom',
      'Snap',
      'Time Machine',
      'Backup',
      'Wifi',
      'Network',
      'Conference',
      'Call',
      'Long Distance',
      'Operator',
      'Telegram',
      'Iceberg',
      'Lettuce',
      'Bacon',
      'Tomato',
      'Sandwich',
      'Subway',
      'Ticket',
      'Pass',
      'Transit',
      'Change',
      'Coins',
      'Collection',
      'Appraisal',
      'Auction',
      'Winner',
      'Loss',
      'Toss',
      'Boss',
      'Floss',
      'Resolution',
      'Image',
      'File',
      'Compress',
      'Zip',
      'Sleeping',
      'Beep',
      'Agility',
      'Endurance',
      'Strength',
      'Wisdom',
      'Magic',
      'Sword',
      'Axe',
      'Hat',
      'Boots',
      'Gloves',
      'Necklace',
      'Helmet',
      'Rod',
      'Cone',
      'Cube',
      'Sphere',
      'Rectangle',
      'Prism',
      'Pyramid',
      'Tower',
      'Skyscraper',
      'Block',
      'Street',
      'Shop',
      'Community',
      'Park',
      'Swing',
      'Climb',
      'Run',
      'Walk',
      'Hike',
      'Fly',
      'Travel',
      'Souvenir',
      'Clutter',
      'Simple',
      'Complex',
      'Tidy',
      'Mess',
      'Filth',
      'Spotless',
      'Spill',
      'Wipe',
      'Scrub',
      'Sweat',
      'Burn',
      'Healing',
      'Heat Stroke',
      'Cold',
      'Freeze',
      'Melt',
      'Condense',
      'Edit',
      'Revisions',
      'Gossip',
      'Rumours',
      'Sassy',
      'Attitude',
      'Altitude',
      'Spin',
      'Charge',
      'Magnetism',
      'Electric',
      'Light',
      'Lightning',
      'Thunderbolt',
      'Static',
      'Rocket',
      'Space',
      'Explore',
      'Discover',
      'Physics',
      'Biology',
      'Literature',
      'Language',
      'Political',
      'Economics',
      'Education',
      'Gradual',
      'Hurry',
      'Curl',
      'Twist',
      'Flip',
      'Tumble',
      'Psychology',
      'Fumble',
      'Bumblebee',
      'Wasp',
      'Ant',
      'Termite',
      'Nest',
      'Bird',
      'Watching',
      'Spying',
      'Snooping',
      'Private',
      'Public',
      'Zero',
      'One',
      'Two',
      'Three',
      'Four',
      'Five',
      'Six',
      'Seven',
      'Eight',
      'Nine',
      'Ten',
      'One Hundred',
      'A Thousand',
      'A Million',
      'Money',
      'Inheritance',
      'Will',
      'Legal',
      'Circumvent',
      'Wind',
      'Sunny',
      'Snowy',
      'Rainy',
      'Cloudy',
      'Tornado',
      'Storm',
      'Flood',
      'Heat Wave',
      'Nature',
      'Artificial',
      'Factory',
      'Assembly',
      'Program',
      'Funding',
      'Scholarship',
      'Grant',
      'Loan',
      'Interest',
      'Debt',
      'Finances',
      'Secretary',
      'Organize',
      'Admin',
      'Management',
      'Strange',
      'Beauty',
      'Charm',
      'Quirky',
      'Top',
      'Bottom',
      'Over',
      'Under',
      'Around',
      'Through',
      'Beside',
      'Inside',
      'Outside',
      'Surround',
      'Sound',
      'Touch',
      'Hear',
      'Listen',
      'Taste',
      'Head',
      'Hair',
      'Hand',
      'Arm',
      'Leg',
      'Wrist',
      'Elbow',
      'Shoulder',
      'Eyes',
      'Nose',
      'Mouth',
      'Face',
      'Ears',
      'Beard',
      'Forehead',
      'Neck',
      'Waist',
      'Knee',
      'Ankle',
      'Feet',
      'Toes',
      'Heel',
      'Chart',
      'Medicine',
      'Operate',
      'Control',
      'Coordinate',
      'Execute',
      'Orchestrate',
      'Plan',
      'Produce',
      'Build',
      'Graph',
      'Create',
      'Design',
      'Develop',
      'Found',
      'Establish',
      'Formal',
      'Casual',
      'Incorporated',
      'Initiate',
      'Institute',
      'Formula',
      'Introduction',
      'Conclusion',
      'Footnotes',
      'Pioneer',
      'Voyage',
      'Accelerate',
      'Brakes',
      'Achievement',
      'Advance',
      'Capital',
      'Booster',
      'Delivery',
      'Expand',
      'Contract',
      'Gain',
      'Generate',
      'Maximum',
      'Minimum',
      'Simulation',
      'Clarity',
      'Central',
      'Custom',
      'Redesign',
      'Renovate',
      'Merge',
      'Yield',
      'Replace',
      'Reduce',
      'Standard',
      'Streamline',
      'Update',
      'Upgrade',
      'Align',
      'Cultivate',
      'Hire',
      'Inspire',
      'Motivate',
      'Recruit',
      'Rules',
      'Shape',
      'Teach',
      'Train',
      'Singular',
      'Advice',
      'Field',
      'Information',
      'Calculation',
      'Identify',
      'Map',
      'Measure',
      'Quantity',
      'Convince',
      'Illustrate',
      'Persuade',
      'Promotion',
      'Review',
      'Award',
      'Complete',
      'Earn',
      'Showcase',
      'Surpass',
      'Target',
      'Aim',
      'Bullseye',
      'Bow',
      'Port',
    ],
  };

  const buttons = document.querySelectorAll('button');

  for (let button of buttons) {
    button.addEventListener('click', getClickEventHandler(suggestions, 18, 29));
  }
};

document.addEventListener('DOMContentLoaded', function () {
  main();
});
